#!/usr/bin/env bash
source /Users/branislav/Documents/Code/Personal/bash/config.sh

# run some custom sh scripts
alias shmu='. ${GIT_DIR}/shmu'

# Easier navigation: .., ..., ...., .....
alias ..="cd .."
alias cd..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# NPM shortcuts
alias st='npm start'
alias mgls='npm run migrate-latest'

# DIRs for work projects & start them
alias cd-login='cd ${WORK_DIR}login'
alias cd-file='cd ${WORK_DIR}/fileservice'
alias cd-be='cd ${WORK_DIR}/backend'
alias cd-gb='cd ${WORK_DIR}/gotenberg'
alias cd-fe='cd ${WORK_DIR}/frontend'
alias st-login='cd-login && npm start'
alias st-file='cd-file && npm start'
alias st-be='cd-be && npm start'
alias st-gb='cd-gb && docker-compose up -d'
alias st-fe='cd-fe  && npm start'
alias devpwd='echo "6bAnfHTcKzEcGd0" | pbcopy'

# GIT Rebase
alias rebcon='git rebase --continue'
alias rebabt='git rebase --abort'
