#!/usr/bin/env bash

# ZIP FRI TASK
# zip relevant files into named zip file to upload them to fridle

function frizip () {
	cp -r $(pwd)/$1 ~/Desktop
	cd ~/Desktop/$1
	rm *.class
	rm *.ctxt
	cd ..	
	zip Blazek.Branislav.5ZYI11.zip $1/*
}
