#!/usr/bin/env bash

# Script for getting Seeds from Work Server
function seeds () {
	cd '${WORK_DIR}SoftMedic/backend/db/seedCentralCode'
	scp datauser@192.168.212.150:~/centralCode_seeds/seedCentralCode.zip .
	unzip -q -o seedCentralCode.zip
	rm seedCentralCode.zip
	npm run seed-central
	npm run migrate-latest
	cd ../..
}
