#!/bin/bash

# SIMPLE SHMU BASH SCRIPT
# Downloads current meteogram for Zilina, Slovakia
# Branislav Blazek 2022

# move to correct location
cd /tmp
mkdir shmu-temp &> /dev/null
cd shmu-temp

# prepare required parts of link
CITY_ID=31920
DATE_FORMAT=$(date '+%Y%m%d')
HOUR_FORMAT=$(date '+%H')
HOUR_TYPE=$(printf '%02d' $((($HOUR_FORMAT/6-1)*6)))

# paste them into one variable
PARAMS=${CITY_ID}-${DATE_FORMAT}-${HOUR_TYPE}00

# SHMU link
SHMU_LINK=https://www.shmu.sk/data/datanwp/v2/meteogram/al-meteogram_$PARAMS-nwp-.png

# download forecast and open
FILENAME=$PARAMS.png
curl $SHMU_LINK -so $FILENAME
open $FILENAME

# TODO:
# 1. add options to choose from
#	a. city
#	b. hour type
#	c. meteogram type
# 2. find db with citites and theirs ID
# 3. open multiple files
