#!/usr/bin/env bash

# GENERAL FUNCTIONS

# Python3 calculator (alt to EXPR)
function calc () {  python3 -c "print($*)" }

# WORK FUNCTIONS

# Script for getting Seeds from Work Server
function seeds () {
	cd ~/Documents/Code/---WORK-DIR---/backend/db/seedCentralCode
	scp datauser@192.168.212.150:~/centralCode_seeds/seedCentralCode.zip .
	unzip -q -o seedCentralCode.zip
	rm seedCentralCode.zip
	npm run seed-central
	npm run migrate-latest
	cd ../..
}

# Automate git add & commit & push
function rocket (){
	current_branch=$(git rev-parse --abbrev-ref HEAD)
	human_branch_title=${current_branch//-/ }
	git add *
	if [ -z "$1" ]
	then
		git commit -m $human_branch_title
	else
		git commit -m $1
	fi
	git push --set-upstream origin $current_branch
}

# GIT FUNCTIONS

# Create new Branch from DEV Branch
function cb () {
        git checkout dev
        git pull
        git checkout -b $1
}

# Change Branch and Start
function cbs () {
        cb $1
        npm start
}

# Move into another Branch
function co () { git checkout $1 }

# Delete lastly created local Branch
function dellastlocal () { git branch -d "@{-1}" }

# Full Rebase proccess on DEV Branch
function reb (){
        git checkout dev
        git pull
        git checkout -
        git rebase dev
}

# Fix CRLF Problem (usually Windows to MacOS)
function crlf (){
        git config core.autocrlf false
        git rm --cached -r .
        git reset --hard
}
